language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y bash zsh

install:
  - composer self-update
  - composer update $COMPOSER_OPTS

script:
  - phpunit tests
