language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y bash zsh

install:
  - composer self-update
  - composer install --dev --prefer-dist
